# Generated by Django 3.2.4 on 2021-06-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(null=True)),
                ('light', models.CharField(choices=[('с', 'Светолюбивые'), ('т', 'Теневыносливые')], max_length=1)),
                ('availability', models.BooleanField()),
            ],
        ),
    ]
