# Generated by Django 3.2.4 on 2021-06-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plants_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='img',
            field=models.ImageField(upload_to='static/images/plants/'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='light',
            field=models.CharField(choices=[('Светолюбивые', 'с'), ('т', 'Теневыносливые')], max_length=30),
        ),
    ]
