# Generated by Django 3.2.4 on 2021-06-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210623_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='static/images/forPlants/')),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('volume', models.IntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OceanTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='static/images/oceanTheme/')),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='plants',
            name='light',
            field=models.CharField(choices=[('Светолюбивое', 'Светолюбивые'), ('Теневыносливое', 'Теневыносливые')], max_length=30),
        ),
    ]
